apiVersion: v1
kind: Service
metadata:
  name: sayhello-server
  namespace: demo
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"50051":{}}}'  # Creates a standalone NEG
spec:
  selector:
    app: sayhello-server
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP  # Keep it internal — Traffic Director uses NEGs, not an external LB