apiVersion: v1
kind: Service
metadata:
  name: sayhello-server
  namespace: demo
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"50051":{}}, "neg-type": "GCE_VM_IP_PORT"}'
    networking.gke.io/enable-traffic-director: "true"
spec:
  selector:
    app: sayhello-server
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP
