apiVersion: v1
kind: ServiceAccount
metadata:
  name: sayhello-server
  namespace: demo
  annotations:
    iam.gke.io/gcp-service-account: sayhello-server@traffic-director-466922.iam.gserviceaccount.com
