apiVersion: apps/v1
kind: Deployment
metadata:
  name: sayhello-client
  namespace: demo
  labels:
    app: sayhello-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sayhello-client
  template:
    metadata:
      labels:
        app: sayhello-client
    spec:
      serviceAccountName: sayhello-client
      containers:
      - name: client
        image: gcr.io/traffic-director-466922/td-app-client:latest
        env:
        - name: GRPC_XDS_BOOTSTRAP
          value: /etc/grpc/bootstrap.json
        - name: GOOGLE_CLOUD_PROJECT
          value: traffic-director-466922
        volumeMounts:
        - name: grpc-bootstrap
          mountPath: /etc/grpc
          readOnly: true
      volumes:
      - name: grpc-bootstrap
        configMap:
          name: grpc-xds-bootstrap
