apiVersion: v1
kind: Service
metadata:
  name: sayhello-client
  namespace: demo
spec:
  selector:
    app: sayhello-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
